import {
  CURRENCY, GHANA_REGIONS, SUPABASE_ANON_KEY, estimateDeliveryFee, formatMoney, functionUrl,
} from '../config.js';
import {
  getCart, removeFromCart, updateQuantity, increaseQuantity, decreaseQuantity, getMaxQuantity, getSubtotal, clearCart,
} from './cart.js';

const escapeHtml = (value = '') => String(value)
  .replaceAll('&', '&amp;')
  .replaceAll('<', '&lt;')
  .replaceAll('>', '&gt;')
  .replaceAll('"', '&quot;')
  .replaceAll("'", '&#039;');

const getLineMeta = (item) => [
  item.brand,
  item.colour,
  item.size ? `Size ${item.size}` : '',
  item.isPreorder ? 'Pre-order' : '',
].filter(Boolean).join(' / ');

// Reads live fulfilment/region state straight from the static form — safe since the
// form itself is never regenerated by render(), only #cart-lines/#order-summary are.
const getSelectedFulfilment = () => document.querySelector('input[name="fulfilment_method"]:checked')?.value || 'delivery';
const getSelectedRegion = () => document.querySelector('[data-region-select]')?.value || '';

const render = () => {
  const cart = getCart();
  const lines = document.querySelector('#cart-lines');
  const summary = document.querySelector('#order-summary');
  const form = document.querySelector('#checkout-form');

  if (!lines || !summary) return;

  if (form) form.hidden = !cart.length;

  if (!cart.length) {
    lines.innerHTML = `
      <div class="empty-state">
        <p>Your bag is ready for a pair worth wearing every day.</p>
        <a class="text-link" href="shop.html">Browse the edit -></a>
      </div>
    `;
    summary.innerHTML = '';
    return;
  }

  lines.innerHTML = cart.map((item) => {
    const productUrl = `product.html?slug=${encodeURIComponent(item.slug || item.productId || '')}`;
    const quantity = Number(item.quantity || 1);
    const max = getMaxQuantity(item);

    return `
      <div class="cart-line">
        <a class="cart-line-image" href="${escapeHtml(productUrl)}" aria-label="View ${escapeHtml(item.name)}">
          <img src="${escapeHtml(item.image || '')}" alt="${escapeHtml(item.name)}">
        </a>
        <div>
          <h2><a href="${escapeHtml(productUrl)}">${escapeHtml(item.name)}</a></h2>
          <p>${escapeHtml(getLineMeta(item))}</p>
          <p>${formatMoney(item.price)}</p>
          <button class="remove-line" type="button" data-remove="${escapeHtml(item.id)}">Remove</button>
        </div>
        <div class="qty-stepper" role="group" aria-label="Quantity for ${escapeHtml(item.name)}">
          <button type="button" data-decrease="${escapeHtml(item.id)}" aria-label="Decrease quantity" ${quantity <= 1 ? 'disabled' : ''}>&minus;</button>
          <input class="line-qty" data-quantity="${escapeHtml(item.id)}" type="number" min="1" max="${max}" value="${quantity}" aria-label="Quantity for ${escapeHtml(item.name)}">
          <button type="button" data-increase="${escapeHtml(item.id)}" aria-label="Increase quantity" ${quantity >= max ? 'disabled' : ''}>&plus;</button>
        </div>
        <strong>${formatMoney(Number(item.price || 0) * quantity)}</strong>
      </div>
    `;
  }).join('');

  const subtotal = getSubtotal(cart);
  const deliveryFee = estimateDeliveryFee(getSelectedFulfilment(), getSelectedRegion());
  const deliveryKnown = deliveryFee !== null;
  const total = subtotal + (deliveryKnown ? deliveryFee : 0);

  summary.innerHTML = `
    <h2>Summary</h2>
    <div class="summary-row"><span>Subtotal</span><strong>${formatMoney(subtotal)}</strong></div>
    <div class="summary-row"><span>Delivery</span><strong>${deliveryKnown ? formatMoney(deliveryFee) : 'Select a region'}</strong></div>
    <div class="summary-total"><span>${deliveryKnown ? 'Total now' : 'Total (excl. delivery)'}</span><strong>${formatMoney(total)}</strong></div>
    <button class="button button-dark checkout-button" type="submit" form="checkout-form">Place order</button>
    <p class="fine-print">Payments are processed securely by Paystack. Currency: ${escapeHtml(CURRENCY)}.</p>
    <div class="checkout-notice" data-checkout-notice></div>
  `;

  document.querySelectorAll('[data-remove]').forEach((button) => {
    button.addEventListener('click', () => {
      removeFromCart(button.dataset.remove);
      render();
    });
  });

  document.querySelectorAll('[data-quantity]').forEach((input) => {
    input.addEventListener('change', () => {
      updateQuantity(input.dataset.quantity, Number(input.value));
      render();
    });
  });

  document.querySelectorAll('[data-increase]').forEach((button) => {
    button.addEventListener('click', () => {
      increaseQuantity(button.dataset.increase);
      render();
    });
  });

  document.querySelectorAll('[data-decrease]').forEach((button) => {
    button.addEventListener('click', () => {
      decreaseQuantity(button.dataset.decrease);
      render();
    });
  });
};

const populateRegionSelect = () => {
  const select = document.querySelector('[data-region-select]');
  if (!select) return;

  select.innerHTML = [
    '<option value="">Select region</option>',
    ...GHANA_REGIONS.map((region) => `<option value="${escapeHtml(region)}">${escapeHtml(region)}</option>`),
  ].join('');
};

// Delivery fields are only relevant (and only required) when fulfilment is "delivery".
// Toggling `required` here, not just visibility, matters: a hidden-but-required field
// can silently block form submission with no visible error for the customer.
const syncFulfilment = () => {
  const deliveryFields = document.querySelector('[data-delivery-fields]');
  if (!deliveryFields) return;

  const method = document.querySelector('input[name="fulfilment_method"]:checked')?.value || 'delivery';
  const isDelivery = method === 'delivery';

  deliveryFields.hidden = !isDelivery;
  deliveryFields.querySelectorAll('input, select, textarea').forEach((field) => {
    field.required = isDelivery;
  });
};

// Builds the payload the create-order Edge Function receives. Deliberately excludes
// price, unit price, subtotal and total: the browser's numbers are for the customer's own
// preview only. The Edge Function looks up real prices and stock from variant_id and
// computes the authoritative order total itself — never trust figures the browser sends.
const buildOrderPayload = (form, cart) => {
  const data = new FormData(form);
  const fulfilmentMethod = data.get('fulfilment_method');
  const isDelivery = fulfilmentMethod === 'delivery';

  return {
    customer: {
      full_name: data.get('full_name')?.trim() || '',
      phone: data.get('phone')?.trim() || '',
      email: data.get('email')?.trim() || null,
    },
    fulfilment_method: fulfilmentMethod,
    delivery: isDelivery ? {
      region: data.get('delivery_region') || '',
      city: data.get('delivery_city')?.trim() || '',
      area: data.get('delivery_area')?.trim() || '',
      address: data.get('delivery_address')?.trim() || '',
    } : null,
    customer_note: data.get('customer_note')?.trim() || null,
    items: cart.map((item) => ({
      product_id: item.productId,
      variant_id: item.variantId,
      quantity: item.quantity,
    })),
    currency: CURRENCY,
  };
};

const setSubmitLoading = (isLoading) => {
  const button = document.querySelector('.checkout-button');
  if (!button) return;
  button.disabled = isLoading;
  button.textContent = isLoading ? 'Placing order…' : 'Place order';
};

const showNotice = (message, isError) => {
  const notice = document.querySelector('[data-checkout-notice]');
  if (!notice) return;
  notice.textContent = message;
  notice.classList.toggle('checkout-notice-error', Boolean(isError));
};

const initCheckoutForm = () => {
  const form = document.querySelector('#checkout-form');
  if (!form) return;

  populateRegionSelect();
  syncFulfilment();

  form.querySelectorAll('input[name="fulfilment_method"]').forEach((radio) => {
    radio.addEventListener('change', () => {
      syncFulfilment();
      render();
    });
  });

  document.querySelector('[data-region-select]')?.addEventListener('change', render);

  form.addEventListener('submit', async (event) => {
    event.preventDefault();

    const cart = getCart();
    if (!cart.length) return;

    if (!form.checkValidity()) {
      form.reportValidity();
      return;
    }

    const payload = buildOrderPayload(form, cart);

    setSubmitLoading(true);
    showNotice('', false);

    try {
      const response = await fetch(functionUrl('create-order'), {
        method: 'POST',
        headers: {
          'Content-Type': 'application/json',
          Authorization: `Bearer ${SUPABASE_ANON_KEY}`,
        },
        body: JSON.stringify(payload),
      });

      const result = await response.json().catch(() => null);

      if (!response.ok || !result?.authorization_url) {
        showNotice(result?.message || 'Something went wrong placing your order. Please try again.', true);
        setSubmitLoading(false);
        return;
      }

      clearCart();
      window.location.href = result.authorization_url;
    } catch {
      showNotice('Could not reach the server. Check your connection and try again.', true);
      setSubmitLoading(false);
    }
  });
};

render();
initCheckoutForm();
window.addEventListener('cart-updated', render);
