// Regenerates sitemap.xml from the live catalogue. This is a static site with no build step,
// so there's nothing that runs this automatically — re-run it by hand (`node
// scripts/generate-sitemap.mjs`) after adding/removing/deactivating products, or whenever the
// static page list below changes. Uses the public anon key only (same as the storefront itself,
// same tables the storefront reads) — no admin auth needed.

import { writeFile } from 'node:fs/promises';

const SUPABASE_URL = 'https://huyfpjqgjtihttctdxdc.supabase.co';
const ANON_KEY = 'sb_publishable_lKjjB6s-vVzT9VoU2cR6WQ_7fxZSCOi';
const SITE_URL = 'https://slidesol.com';

const STATIC_PAGES = [
  { path: '/', changefreq: 'weekly', priority: '1.0' },
  { path: '/shop.html', changefreq: 'daily', priority: '0.9' },
  { path: '/contact.html', changefreq: 'monthly', priority: '0.5' },
  { path: '/about.html', changefreq: 'monthly', priority: '0.4' },
  { path: '/faq.html', changefreq: 'monthly', priority: '0.4' },
  { path: '/size-guide.html', changefreq: 'monthly', priority: '0.4' },
  { path: '/terms.html', changefreq: 'yearly', priority: '0.2' },
];

const res = await fetch(`${SUPABASE_URL}/rest/v1/products?select=slug&is_active=eq.true&order=slug`, {
  headers: { apikey: ANON_KEY, Authorization: `Bearer ${ANON_KEY}` },
});
if (!res.ok) {
  console.error('Failed to fetch products', res.status, await res.text());
  process.exit(1);
}
const products = await res.json();

const urlEntry = (loc, changefreq, priority) => `  <url>
    <loc>${loc}</loc>
    <changefreq>${changefreq}</changefreq>
    <priority>${priority}</priority>
  </url>`;

const entries = [
  ...STATIC_PAGES.map((p) => urlEntry(`${SITE_URL}${p.path}`, p.changefreq, p.priority)),
  ...products.map((p) => urlEntry(`${SITE_URL}/product.html?slug=${encodeURIComponent(p.slug)}`, 'weekly', '0.7')),
];

const xml = `<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by scripts/generate-sitemap.mjs — re-run it by hand after catalogue changes,
     there's no build step to do this automatically. Product URLs use the bare ?slug= form
     (no &colour=) since that's the canonical URL product.html itself declares — colour-specific
     links are the same page/content, not a distinct URL worth listing separately.
     checkout.html, order-success.html, and wishlist.html are excluded (transactional or
     per-visitor, nothing there for a crawler to index); /admin/ is excluded via robots.txt. -->
<urlset xmlns="http://www.sitemaps.org/schemas/sitemap/0.9">
${entries.join('\n')}
</urlset>
`;

await writeFile(new URL('../sitemap.xml', import.meta.url), xml);
console.log(`Wrote sitemap.xml: ${STATIC_PAGES.length} static pages + ${products.length} products = ${STATIC_PAGES.length + products.length} URLs.`);
